INSERT INTO GENRE (ID,LIBELLE) VALUES ('1','Action');
INSERT INTO GENRE (ID,LIBELLE) VALUES ('2','Comédie');
INSERT INTO GENRE (ID,LIBELLE) VALUES ('3','Anime');
INSERT INTO GENRE (ID,LIBELLE) VALUES ('4','Horreur');

INSERT INTO STATUT_VISIONNAGE (ID,LIBELLE) VALUES ('1','Vu');
INSERT INTO STATUT_VISIONNAGE (ID,LIBELLE) VALUES ('2','En cours');
INSERT INTO STATUT_VISIONNAGE (ID,LIBELLE) VALUES ('3','A voir');

--INSERT INTO OEUVRE (ID,TYPE_OEUVRE,TITRE,GENRE_OEUVRE_ID,STATUT_VISIONNAGE_ID,NOTE,VIDEO,DUREE) VALUES ('1','film','Shazam!',2,3,4,null, 131);
--INSERT INTO OEUVRE (ID,TYPE_OEUVRE,TITRE,GENRE_OEUVRE_ID,STATUT_VISIONNAGE_ID,NOTE,VIDEO,DUREE) VALUES ('2','film','Shazam!',2,3,4,null, 131);

