DELETE FROM STATUT_VISIONNAGE;
DELETE FROM GENRE;

INSERT INTO GENRE (ID,LIBELLE) VALUES (1,'Action');
INSERT INTO GENRE (ID,LIBELLE) VALUES (2,'Comédie');
INSERT INTO GENRE (ID,LIBELLE) VALUES (3,'Anime');
INSERT INTO GENRE (ID,LIBELLE) VALUES (4,'Horreur');

INSERT INTO STATUT_VISIONNAGE (ID,LIBELLE) VALUES (1,'A voir');
INSERT INTO STATUT_VISIONNAGE (ID,LIBELLE) VALUES (2,'En cours');
INSERT INTO STATUT_VISIONNAGE (ID,LIBELLE) VALUES (3,'Vu');
