DELETE FROM STATUT_VISIONNAGE;
DELETE FROM GENRE;

INSERT INTO GENRE (LIBELLE) VALUES ('Action');
INSERT INTO GENRE (LIBELLE) VALUES ('Comédie');
INSERT INTO GENRE (LIBELLE) VALUES ('Anime');
INSERT INTO GENRE (LIBELLE) VALUES ('Horreur');

INSERT INTO STATUT_VISIONNAGE (LIBELLE) VALUES ('A voir');
INSERT INTO STATUT_VISIONNAGE (LIBELLE) VALUES ('En cours');
INSERT INTO STATUT_VISIONNAGE (LIBELLE) VALUES ('Vu');
