DELETE FROM UTILISATEUR_ROLES;
DELETE FROM UTILISATEUR;

INSERT INTO UTILISATEUR (LOGIN,MOT_DE_PASSE) VALUES ('u1','$2a$10$komMkYiUa3kiE9kRZvtIyO07pLDO0DXupleReWnirs..6LmFFExEO');
INSERT INTO UTILISATEUR_ROLES(UTILISATEUR_ID, ROLES) VALUES (1,'ROLE_USER');
