DELETE FROM UTILISATEUR_ROLES;
DELETE FROM UTILISATEUR;

INSERT INTO UTILISATEUR (LOGIN,MOT_DE_PASSE) VALUES ('olivier','$2a$10$rLR5RZYJqThVB/b3ukCcHu75bEs/IyN82K5EBXAGMInIr7Zd942zC');
INSERT INTO UTILISATEUR_ROLES(UTILISATEUR_ID, ROLES) VALUES (1,'ROLE_USER');

INSERT INTO UTILISATEUR (LOGIN,MOT_DE_PASSE) VALUES ('fabien','$2a$10$T1IpSEGamlZmA98Nlw4PierRLpXDmclpTNqR6.Ld2t/ZpsvMgkFZi');
INSERT INTO UTILISATEUR_ROLES(UTILISATEUR_ID, ROLES) VALUES (2,'ROLE_USER');
